questions = {
    "Which element has the highest electronegativity?": "A",
    "What is the molecular formula of butane?": "C",
    "Which acid is known as the king of chemicals?": "B",
    "What is the electron configuration of the calcium ion (Ca²⁺)?": "D",
    "What is the bond angle in a water molecule?": "D",
    "What is the pH of a neutral solution at 25°C?": "A",
    "Which of the following is a strong base?": "A",
    "What type of bond forms between two non-metals?": "C",
    "What is the main gas found in the air we breathe?": "D",
    "Which process is used to separate a liquid mixture into its components?": "C",
    "Which law states that pressure is inversely proportional to volume?": "C",
    "What is the chemical name for baking soda?": "B",
    "Which of the following is an allotrope of carbon?": "B",
    "What is the primary force holding together ionic compounds?": "A",
    "Which of the following substances is most acidic?": "D",
    "What is the atomic number of carbon?": "A",
    "What is the empirical formula of glucose (C6H12O6)?": "D",
    "Which functional group is present in alcohols?": "C",
    "What is the hybridization of carbon in methane (CH4)?": "B",
    "Which gas is commonly used in light bulbs?": "A"
}

choices = [["A. Fluorine", "B. Oxygen", "C. Nitrogen", "D. Chlorine"],
           ["A. C3H8", "B. C5H12", "C. C4H10", "D. C4H8"],
           ["A. Sulfuric Acid", "B. Hydrochloric Acid", "C. Nitric Acid", "D. Phosphoric Acid"],
           ["A. [Ne] 3s2", "B. [Kr]", "C. [Ar]", "D. [Ar] 4s2"],
           ["A. 104.5°", "B. 109.5°", "C. 120°", "D. 180°"],
           ["A. 7", "B. 0", "C. 10", "D. 14"],
           ["A. NH3", "B. CH3COOH", "C. HCl", "D. NaOH"],
           ["A. Ionic", "B. Metallic", "C. Hydrogen", "D. Covalent"],
           ["A. Oxygen", "B. Carbon Dioxide", "C. Argon", "D. Nitrogen"],
           ["A. Filtration", "B. Evaporation", "C. Chromatography", "D. Distillation"],
           ["A. Charles's Law", "B. Avogadro's Law", "C. Dalton's Law", "D. Boyle's Law"],
           ["A. Calcium carbonate", "B. Sodium chloride", "C. Ammonium nitrate", "D. Sodium bicarbonate"],
           ["A. Sodium", "B. Sulfur", "C. Aluminum", "D. Graphite"],
           ["A. Dipole-dipole", "B. Hydrogen bonds", "C. London dispersion", "D. Ionic bonds"],
           ["A. Pure water", "B. Blood", "C. Soap solution", "D. Lemon juice"],
           ["A. 12", "B. 8", "C. 14", "D. 6"],
           ["A. CH", "B. C2H4O2", "C. C6H12O6", "D. CH2O"],
           ["A. Carboxyl group", "B. Amino group", "C. Ketone group", "D. Hydroxyl group"],
           ["A. sp", "B. sp2", "C. dsp3", "D. sp3"],
           ["A. Helium", "B. Nitrogen", "C. Xenon", "D. Argon"]]